[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[build.healthcheck]
timeout = 300

[build.nixpacks]
configPath = "nixpacks.toml"